FROM tiger0421/ros-gpu-gazebo:ros-tensorflow-gpu

ARG DOCKER_USER=docker

WORKDIR /home/${DOCKER_USER}/catkin_ws/src
RUN chown -R ${DOCKER_USER}:${DOCKER_USER} /home/${DOCKER_USER}/catkin_ws
COPY docker-entrypoint.sh /tmp
RUN chmod 777 /tmp/docker-entrypoint.sh
USER ${DOCKER_USER}
ENTRYPOINT ["/tmp/docker-entrypoint.sh"]
RUN echo source /home/${DOCKER_USER}/catkin_ws/devel/setup.bash >> /home/${DOCKER_USER}/.bashrc

CMD ["/bin/bash"]

WORKDIR /home/${DOCKER_USER}
