FROM tiger0421/ros-gpu-gazebo:1.0-glvnd-runtime-ubuntu18.04

ARG DOCKER_UID=1000
ARG DOCKER_USER=docker
ARG DOCKER_PASSWORD=docker
RUN useradd -m --uid ${DOCKER_UID} --groups sudo ${DOCKER_USER} \
  && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd

RUN pip install setuptools google-auth --upgrade
RUN pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.1.0-cp27-cp27mu-manylinux2010_x86_64.whl

WORKDIR /home/${DOCKER_USER}/catkin_ws/src
RUN chown -R ${DOCKER_USER}:${DOCKER_USER} /home/${DOCKER_USER}/catkin_ws
COPY docker-entrypoint.sh /tmp
RUN chmod 777 /tmp/docker-entrypoint.sh
USER ${DOCKER_USER}
ENTRYPOINT ["/tmp/docker-entrypoint.sh"]
RUN echo source /home/${DOCKER_USER}/catkin_ws/devel/setup.bash >> /home/${DOCKER_USER}/.bashrc

CMD ["/bin/bash"]

WORKDIR /home/${DOCKER_USER}
